---
- hosts: gke_cluster
  gather_facts: false
  connection: local
  become: false

  tasks:

  - name: Install Argo CD
    k8s:
      state: present
      src: k8s-manifest-light.yml
      kubeconfig: ~/.kube/config
      namespace: argocd
      validate_certs: no
      verify_ssl: no

  - name: Wait for Argo CD API server to become ready
    k8s:
      api_version: v1
      kind: Pod
      namespace: argocd
      name: argocd-server
      wait: yes
      wait_condition:
        type: Ready
        status: True