---
- hosts: gke_cluster
  gather_facts: false
  connection: local
  become: false

  tasks:

  - name: Add Argo Helm repository
    shell: helm repo add argo https://argoproj.github.io/argo-helm

  - name: Update Helm repository
    shell: helm repo update

  - name: Install Argo CD
    shell: helm install --force --set server.container.image=argoproj/argocd-server:v2.4.3 argocd argo/argo-cd --namespace argocd

  - name: Wait for Argo CD API server to become ready
    k8s:
      api_version: v1
      kind: Pod
      namespace: argocd
      name: argocd-server
      wait: yes
      wait_condition:
        type: Ready
        status: True