#cloud-init.yaml

write_files:
  - path: /home/ubuntu/app.py
    content: |
      from flask import Flask

      app = Flask(__name__)

      @app.route("/")
      def hello():
          return "Hello, Terraform from Cloud-Init!"

      if __name__ == "__main__":
          app.run(host="0.0.0.0", port=80)

runcmd:
  - sudo apt update -y
  - sudo apt install -y python3 python3-pip
  - pip3 install Flask
  - nohup python3 /home/ubuntu/app.py > /home/ubuntu/flask.log 2>&1 &