name: Deploy GKE Cluster

on:
  # push:
    # branches:
    #   - "main"
    # paths:
    #   - 'TerraformOnGCP/k8s-argocd-monitoring-with-github-workflow/**'
  workflow_dispatch:

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    defaults:
      run:
        shell: bash
        working-directory: ./TerraformOnGCP/k8s-argocd-monitoring-with-github-workflow

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.GCP_ACCESS_KEY }}
          project_id: cloud-2255

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: cloud-2255          

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Initialize Terraform
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        id: plan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan