# ---
# controller:
#   config:
#     compute-full-forwarded-for: "true"
#     use-forwarded-headers: "true"
#     proxy-body-size: "0"
#   ingressClassResources:
#     name: external-nginx
#     enabled: true
#     default: false
#   affinity:
#     podAntiAffinity:
#       requiredDuringSchedulingIgnoredDuringExecution:
#       - labelSelector:
#           matchExpressions:
#           - key: app.kubernetes.io/name
#             operator: In
#             values:
#             - ingress-nginx
#         topologyKey: "kubernetes.io/hostname"
#   replicaCount: 1
#   additionWebhooks:
#     enabled: true
#   service:
#     annotations:
#       cloud.google.com/load-balancer-type: External
#   metrics:
#     enabled: false