# defines the Kubernetes Service for accessing the Grafana UI

apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: grafana
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 11.5.2
  name: grafana
  namespace: monitoring
spec:
  type: LoadBalancer # This line tells Kubernetes to create a Service of type LoadBalancer. GKE will automatically provision a Google Cloud Load Balancer and assign it an external IP address.
  ports:
  - name: http # A name for the port
    port: 3000 # This is the external port that the Service will listen on. 3000 is the default Grafana port
    targetPort: http # This refers to the port inside the Grafana container. http is likely defined as port 3000 in container.
  selector:
    app.kubernetes.io/component: grafana
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: kube-prometheus