apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: kube-state-metrics
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 2.15.0
  name: kube-state-metrics
  namespace: kube-system
spec:
  clusterIP: None # A headless service doesn't have a single cluster IP address; instead, DNS resolves directly to the IP addresses of the pods selected by the service. This is often used for stateful applications and for services where you need to access individual pods directly.
  ports:
  - name: https-metrics
    port: 8080
    targetPort: 8080
  - name: telemetry
    port: 8081
    targetPort: 8081
  selector: # This will match the pods created by your kubeStateMetrics-deployment.yaml
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: kube-state-metrics
    app.kubernetes.io/part-of: kube-prometheus