apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-server  # More specific name
  labels:
    app: prometheus-server  # Consistent labels
    component: server
    app.kubernetes.io/version: 2.51.1  # Use your *Prometheus server* version here!
rules:
- apiGroups: [""]
  resources:
  - nodes
  - nodes/metrics
  - services
  - endpoints
  - pods
  - configmaps
  verbs: ["get", "list", "watch"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]