name: Deploy Application

on:
  workflow_run:
    workflows: ["Deploy GKE Cluster"]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.GCP_ACCESS_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          install_components: gke-gcloud-auth-plugin

      - name: Configure gcloud and kubectl
        run: |
            mkdir -p $GITHUB_WORKSPACE/GCP
            cp /home/runner/work/GCP/GCP/gha-creds-eb30bdd8b2eee6a1.json $GITHUB_WORKSPACE/GCP/
            gcloud auth activate-service-account --key-file=$GITHUB_WORKSPACE/GCP/gha-creds-eb30bdd8b2eee6a1.json
            gcloud config set project $GCP_PROJECT
            gcloud container clusters get-credentials gke-cluster --zone us-central1-f --project $GCP_PROJECT
            kubectl config set-context --current --namespace=default
            kubectl config set-credentials gke_$GCP_PROJECT_us-central1-f_gke-cluster --exec-command=gcloud --exec-namespace=kubernetes.io --exec-api-version=client.authentication.k8s.io/v1alpha1 --exec-arg=--command=gke-gcloud-auth-plugin --exec-arg=-- --exec-arg=get-token --exec-env=GOOGLE_APPLICATION_CREDENTIALS=$GITHUB_WORKSPACE/GCP/gha-creds-eb30bdd8b2eee6a1.json
            kubectl get clusterrolebindings
            kubectl get pods -A
        shell: bash
        env:
            GCP_PROJECT: $GCP_PROJECT
            GOOGLE_APPLICATION_CREDENTIALS: $GITHUB_WORKSPACE/GCP/gha-creds-eb30bdd8b2eee6a1.json

      - name: Create Argo CD Namespace
        run: kubectl create namespace argocd

      - name: Deploy Nginx
        run: kubectl apply -f k8s-configs/deployment.yml

      - name: Deploy LoadBalancer and Ingress
        run: kubectl apply -f k8s-configs/lb-and-ingress-svc.yml

      - name: Create Ansible Inventory Directory
        run: mkdir -p ansible/inventory
      - name: Set up Terraform # Required for Ansible inventory
        uses: hashicorp/setup-terraform@v2
      - name: Initialize Terraform
        run: terraform init
      - name: Configure Dynamic Inventory (gcp.yml)
        run: |
          cat <<EOF > ansible/inventory/gcp.yml
          plugin: google.cloud.gcp_compute
          projects:
            - ${{ secrets.GCP_PROJECT_ID }}
          regions:
            - $(terraform output -raw cluster_region)
          filters: []
          auth_kind: serviceaccount
          service_account_file: ${{ steps.auth.outputs.credentials_file_path }}
          EOF
        shell: bash

      - name: Install google.cloud collection
        run: ansible-galaxy collection install google.cloud

      - name: Install Argo CD with Helm (Ansible)
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: ansible/playbooks/install-argocd-with-helm.yml
          options: |
            --extra-vars "argocd_namespace=argocd"
            --inventory ansible/inventory/gcp.yml