name: Deploy Application

on:
  workflow_run:
    workflows: ["Deploy GKE Cluster"]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.GCP_ACCESS_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # --- Get Cluster Info from Terraform ---
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Initialize Terraform
        run: terraform init
        working-directory: ./TerraformOnGCP/GKE

      - name: Configure gcloud and kubectl
        run: |
          gcloud container clusters get-credentials gke-cluster --zone us-central1-f --project cloud-2255
          kubectl get pods -A

      - name: Create Argo CD Namespace
        run: kubectl create namespace argocd

      - name: Deploy Nginx
        run: kubectl apply -f k8s-configs/deployment.yml

      - name: Deploy LoadBalancer and Ingress
        run: kubectl apply -f k8s-configs/lb-and-ingress-svc.yml

      - name: Create Ansible Inventory Directory
        run: mkdir -p ansible/inventory

      - name: Configure Dynamic Inventory (gcp.yml)
        run: |
          cat <<EOF > ansible/inventory/gcp.yml
          plugin: google.cloud.gcp_compute
          projects:
            - ${{ secrets.GCP_PROJECT_ID }}
          regions:
            - $(terraform output -raw cluster_region)
          filters: []
          auth_kind: serviceaccount
          service_account_file: ${{ steps.auth.outputs.credentials_file_path }}
          EOF
        shell: bash