name: Deploy Application

on:
  workflow_run:
    workflows: ["Deploy GKE Cluster"]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.GCP_ACCESS_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          install_components: gke-gcloud-auth-plugin

      # --- Get Cluster Info from Terraform ---
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Initialize Terraform
        run: terraform init

      - name: Get Cluster Name
        id: get_cluster_name
        run: echo "cluster_name=$(terraform output -raw cluster_name)" >> "$GITHUB_OUTPUT"
        working-directory: ./TerraformOnGCP/GKE

      - name: Get Cluster Region
        id: get_cluster_region
        run: echo "cluster_region=$(terraform output -raw cluster_region)" >> "$GITHUB_OUTPUT"
        working-directory: ./TerraformOnGCP/GKE
      # --- End Get Cluster Info ---

      - name: Configure gcloud and kubectl
        run: |
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          gcloud container clusters get-credentials "${{ steps.get_cluster_name.outputs.cluster_name }}" --region "${{ steps.get_cluster_region.outputs.cluster_region }}" --project ${{ secrets.GCP_PROJECT_ID }}
          rm -rf ~/.kube
          rm -rf ~/.config/gcloud # clean up to avoid any conflicts.
          gcloud container clusters get-credentials "${{ steps.get_cluster_name.outputs.cluster_name }}" --region "${{ steps.get_cluster_region.outputs.cluster_region }}" --project ${{ secrets.GCP_PROJECT_ID }}
          kubectl get clusterrolebindings  # Requires cluster-admin
          kubectl get pods -A  # Check cluster-level access

      - name: Create Argo CD Namespace
        run: kubectl create namespace argocd
        working-directory: ./TerraformOnGCP/GKE

      - name: Deploy Nginx
        run: kubectl apply -f k8s-configs/deployment.yml
        working-directory: ./TerraformOnGCP/GKE

      - name: Deploy LoadBalancer and Ingress
        run: kubectl apply -f k8s-configs/lb-and-ingress-svc.yml
        working-directory: ./TerraformOnGCP/GKE

        # we will uncomment this step if we would like have customize nginx/argocd config and create a config map for it (this file also exist and we can uncomment and use it)
    #   - name: Wait for LoadBalancer IPs
    #     id: get_lb_ips
    #     run: |
    #       get_lb_ip() {
    #         local service_name=$1
    #         local namespace=$2
    #         local attempts=30
    #         local delay=10
    #         for i in $(seq 1 $attempts); do
    #           ip=$(kubectl get service "$service_name" -n "$namespace" -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
    #           if [[ -n "$ip" ]]; then
    #             echo "$ip"
    #             return 0
    #           fi
    #           echo "Waiting for LoadBalancer IP for $service_name in $namespace (attempt $i/$attempts)..."
    #           sleep "$delay"
    #         done
    #         echo "ERROR: Failed to get LoadBalancer IP for $service_name in $namespace after $attempts attempts." >&2
    #         exit 1
    #       }
    #       ARGOCD_LB_IP=$(get_lb_ip argocd-server-lb argocd)
    #       NGINX_LB_IP=$(get_lb_ip nginx-lb default)
    #       echo "ARGOCD_LB_IP=$ARGOCD_LB_IP" >> "$GITHUB_OUTPUT"
    #       echo "NGINX_LB_IP=$NGINX_LB_IP" >> "$GITHUB_OUTPUT"

    #   - name: Create ConfigMaps
    #     id: create_configmaps
    #     run: |
    #       sed "s|\${NGINX_LB_IP}|${{ steps.get_lb_ips.outputs.NGINX_LB_IP }}|g; s|\${ARGOCD_LB_IP}|${{ steps.get_lb_ips.outputs.ARGOCD_LB_IP }}|g" k8s-configs/config-maps.yml | kubectl apply -f -

      # --- Ansible Setup and Execution ---
      - name: Create Ansible Inventory Directory
        run: mkdir -p ansible/inventory
        working-directory: ./TerraformOnGCP/GKE

      - name: Configure Dynamic Inventory (gcp.yml)
        run: |
          cat <<EOF > ansible/inventory/gcp.yml
          plugin: google.cloud.gcp_compute
          projects:
            - ${{ secrets.GCP_PROJECT_ID }}
          regions:
            - $(terraform output -raw cluster_region) # now you can have dynamic region
          filters: []
          auth_kind: serviceaccount
          service_account_file: ${{ steps.auth.outputs.credentials_file_path }}
          EOF
        shell: bash
        working-directory: ./TerraformOnGCP/GKE

      - name: Install google.cloud collection
        run: ansible-galaxy collection install google.cloud
        working-directory: ./TerraformOnGCP/GKE

      - name: Install Argo CD with Helm (Ansible)
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: ./TerraformOnGCP/GKE/ansible/playbooks/install-argocd-with-helm.yml
          options: |
            --extra-vars "argocd_namespace=argocd"
            --inventory ./TerraformOnGCP/GKE/ansible/inventory/gcp.yml