name: Deploy Application

on:
  workflow_run:
    workflows: ["Deploy GKE Cluster"]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.GCP_ACCESS_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          install_components: gke-gcloud-auth-plugin

      - name: Configure gcloud and kubectl
        run: |
            gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
            gcloud container clusters get-credentials gke-cluster --zone us-central1-f --project ${{ secrets.GCP_PROJECT_ID }}
            kubectl config set-context --current --namespace=default
            kubectl config set clusters.gke_${{ secrets.GCP_PROJECT_ID }}_us-central1-f_gke-cluster.auth-provider.config.cmd-args --set="config config-helper --format=json"
            kubectl config set clusters.gke_${{ secrets.GCP_PROJECT_ID }}_us-central1-f_gke-cluster.auth-provider.config.cmd-path --set="$(which gke-gcloud-auth-plugin)"
            kubectl config set clusters.gke_${{ secrets.GCP_PROJECT_ID }}_us-central1-f_gke-cluster.auth-provider.config.expiry-key --set='{.credential.token_expiry}'
            kubectl config set clusters.gke_${{ secrets.GCP_PROJECT_ID }}_us-central1-f_gke-cluster.auth-provider.config.token-key --set='{.credential.access_token}'
            kubectl config set users.gke_${{ secrets.GCP_PROJECT_ID }}_us-central1-f_gke-cluster.auth-provider.name "gcp"
            kubectl get pods -A

      - name: Create Argo CD Namespace
        run: kubectl create namespace argocd

      - name: Deploy Nginx
        run: kubectl apply -f k8s-configs/deployment.yml

      - name: Deploy LoadBalancer and Ingress
        run: kubectl apply -f k8s-configs/lb-and-ingress-svc.yml

      - name: Create Ansible Inventory Directory
        run: mkdir -p ansible/inventory
      - name: Set up Terraform # Required for Ansible inventory
        uses: hashicorp/setup-terraform@v2
      - name: Initialize Terraform
        run: terraform init
      - name: Configure Dynamic Inventory (gcp.yml)
        run: |
          cat <<EOF > ansible/inventory/gcp.yml
          plugin: google.cloud.gcp_compute
          projects:
            - ${{ secrets.GCP_PROJECT_ID }}
          regions:
            - $(terraform output -raw cluster_region)
          filters: []
          auth_kind: serviceaccount
          service_account_file: ${{ steps.auth.outputs.credentials_file_path }}
          EOF
        shell: bash

      - name: Install google.cloud collection
        run: ansible-galaxy collection install google.cloud

      - name: Install Argo CD with Helm (Ansible)
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: ansible/playbooks/install-argocd-with-helm.yml
          options: |
            --extra-vars "argocd_namespace=argocd"
            --inventory ansible/inventory/gcp.yml