name: Deploy GKE Cluster

on:
  push:
    branches:
      - main

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Set service account key environment variable
        run: printf '%s' "${{ secrets.GCP_SA_KEY }}" > gcp-sa-key.json

      - name: Initialize Terraform
        run: terraform init
        working-directory: TerraformOnGCP/GKE

      - name: Apply Terraform configuration
        run: terraform apply -auto-approve
        working-directory: TerraformOnGCP/GKE