name: Install Argo CD

on:
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.GCP_ACCESS_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          install_components: gke-gcloud-auth-plugin
  
      - name: connect to GKE
        run: |
            gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
            gcloud container clusters get-credentials gke-cluster --zone us-central1-f --project ${{ secrets.GCP_PROJECT_ID }}
        env:
            GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
  
       # --- DEBUGGING: Check cluster state BEFORE Helm install ---
      - name: Debug - List Nodes
        run: kubectl get nodes -o wide

      - name: Debug - List Pods (All Namespaces)
        run: kubectl get pods -A -o wide

      - name: Create Argo CD Namespace
        run: kubectl create namespace argocd

      - name: Add Argo Helm repository
        run: helm repo add argo https://argoproj.github.io/argo-helm

      - name: Install Argo CD
        run: |
          helm install argocd argo/argo-cd \
            --namespace argocd \
            --create-namespace \
            --wait --timeout 600s \
            --version "5.16.0" \
            --set server.extraArgs[0]="--insecure" \
            --set server.image.repository=argoproj/argocd \
            --set server.image.tag=v2.9.3 \
            --debug  # Add Helm debug flag

      - name: Wait for a While  # Add a delay before checking status
        run: sleep 60

      # --- DEBUGGING: Check cluster state AFTER Helm install ---
      - name: Debug - List Pods (Argo CD Namespace) - After Install
        run: kubectl get pods -n argocd -o wide

      - name: Debug - Describe Argo CD Server Pod - After Install
        run: kubectl describe pod -n argocd -l app.kubernetes.io/name=argocd-server

      - name: Get Argo CD initial admin password
        id: get_password
        run: |
          PASSWORD=$(kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d)
          echo "password=$PASSWORD" >> "$GITHUB_OUTPUT"

      - name: Output Argo CD Password
        run: |
          echo "Argo CD initial admin password: ${{ steps.get_password.outputs.password }}"
  