name: Install Argo CD

on:
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.GCP_ACCESS_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          install_components: gke-gcloud-auth-plugin
  
      - name: connect to GKE
        run: |
            gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
            gcloud container clusters get-credentials gke-cluster --zone us-central1-f --project ${{ secrets.GCP_PROJECT_ID }}
        env:
            GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
  
       # --- DEBUGGING: Check cluster state BEFORE Helm install ---
      - name: Debug - List Nodes
        run: kubectl get nodes -o wide

      - name: Debug - List Pods (All Namespaces)
        run: kubectl get pods -A -o wide

      - name: Create Argo CD Namespace
        run: kubectl create namespace argocd

      - name: Install Argo CD
        run: |
          kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/v2.14.3/manifests/install.yaml

      - name: Get Argo CD initial admin password
        id: get_password
        run: |
          PASSWORD=$(kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d)
          echo "password=$PASSWORD" >> "$GITHUB_OUTPUT"

      - name: Output Argo CD Password
        run: |
          echo "Argo CD initial admin password: ${{ steps.get_password.outputs.password }}"
