name: Install Prometheus

on:
    workflow_run:
      workflows: ["Install Argo CD"]
      types:
        - completed
    workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    defaults:
      run:
        working-directory: ./TerraformOnGCP/GKE

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.GCP_ACCESS_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          token_format: 'access_token'

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          install_components: gke-gcloud-auth-plugin
  
      - name: connect to GKE
        run: |
            gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
            gcloud container clusters get-credentials gke-cluster --zone us-central1-f --project ${{ secrets.GCP_PROJECT_ID }}
        env:
            GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}

      - name: Install google.cloud collection
        run: ansible-galaxy collection install google.cloud

      - name: create Monitoring namespace
        run: kubectl create namespace monitoring || true

      - name: Add Prometheus Helm Repository
        run: |
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo update

      - name: Install Node Exporter
        run: |
          helm install node-exporter prometheus-community/prometheus-node-exporter \
           --namespace monitoring \
           --create-namespace \
           --wait --timeout 180s

      - name: Install Prometheus with Helm
        run: |
          helm install prometheus prometheus-community/prometheus \
            --namespace monitoring \
            --create-namespace \
            --wait --timeout 600s \
            -f monitoring/prometheus-values.yml \ #this file contains lb svc creation as well
            --debug
        #   --values my-prometheus-values.yaml  # Uncomment and create this file for custom configuration

      # Optional: Verify Installation
      - name: Verify Prometheus Installation
        run: |
          kubectl get pods -n monitoring
          kubectl get svc -n monitoring