name: K8s Ansible Workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up GCP credentials
        run: |
          echo '${{ secrets.SSH_SA_KEY }}' > /tmp/sa-key.json
          echo "GOOGLE_CREDENTIALS=$(cat /tmp/sa-key.json)" >> $GITHUB_ENV
          echo "SSH_SA_EMAIL=${{ secrets.SSH_SA_EMAIL }}" >> $GITHUB_ENV

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          TF_VAR_ssh_sa_email: ${{ secrets.SSH_SA_EMAIL }}