# Deploy k8s cluster and create a VM dedicated to ansible node controller
name: k8s cluster & Ansible Controller

on:
  push:
    branches:
      - "main"
    paths:
      - 'TerraformOnGCP/k8s-argocd-monitoring-with-ansible/**'
  workflow_dispatch:

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    defaults:
      run:
        shell: bash
        working-directory: ./TerraformOnGCP/k8s-argocd-monitoring-with-ansible

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.GCP_ACCESS_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}          

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Initialize Terraform
        run: terraform init

      - name: Terraform Plan
        id: plan
        env:
          TF_VAR_gcp_project_id: ${{ secrets.GCP_PROJECT_ID }}
          TF_VAR_gcp_sa_email: ${{ secrets.GCP_SA_EMAIL }}
          # Add the new variable mapping
          TF_VAR_target_gke_node_user_email: ${{ secrets.GCP_SA_EMAIL }}
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        env:
          TF_VAR_gcp_project_id: ${{ secrets.GCP_PROJECT_ID }}
          TF_VAR_gcp_sa_email: ${{ secrets.GCP_SA_EMAIL }}
          # Add the new variable mapping
          TF_VAR_target_gke_node_user_email: ${{ secrets.GCP_SA_EMAIL }}
        run: terraform apply -auto-approve tfplan
